# Generated by Django 5.2.17 on 2026-09-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('topic', models.CharField(choices=[('general', 'General enquiry'), ('admissions', 'Admissions'), ('academic', 'Academic matters'), ('finance', 'Fees and payments'), ('technical', 'Portal / technical support')], default='general', max_length=16)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField(max_length=5000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
