# Generated by Django 5.2.17 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_grant_attendance_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(choices=[('qr', 'QR code'), ('code', 'Check-in code'), ('lecturer', 'Marked by lecturer'), ('upload', 'Uploaded register'), ('correction', 'Approved correction'), ('system', 'Absent at close')], max_length=12),
        ),
    ]
