# Generated by Django 5.2.17 on 2026-09-23 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Dotted verb, e.g. "payment.void"', max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('summary', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'), models.Index(fields=['target_type', 'target_id'], name='core_auditl_target__6c66b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('registration', 'Course registration'), ('results', 'Results'), ('exams', 'Examinations'), ('finance', 'Fees & payments'), ('admission', 'Admission'), ('accommodation', 'Accommodation'), ('library', 'Library'), ('support', 'Support')], default='general', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Portal path to open, e.g. /results', max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_bd2d4b_idx')],
            },
        ),
    ]
