# Generated by Django 5.2.17 on 2026-09-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Also show this as news on the public website.', verbose_name='Publish on the website'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Show on the website'),
        ),
    ]
