# Generated by Django 5.2.17 on 2026-09-24 10:12

from django.db import migrations, models

VIEWERS = ("hod", "dean", "vc")


def backfill(apps, schema_editor):
    StudentProfile = apps.get_model("accounts", "StudentProfile")
    Semester = apps.get_model("academics", "Semester")
    current = Semester.objects.filter(is_current=True).first()
    for profile in StudentProfile.objects.all():
        profile.student_id = f"STU{profile.pk:07d}"
        if current and not profile.current_session:
            profile.current_session = current.session
        profile.save(update_fields=["student_id", "current_session"])
    Role = apps.get_model("accounts", "Role")
    for role in Role.objects.filter(code__in=VIEWERS):
        if "students.view" not in role.permissions:
            role.permissions = [*role.permissions, "students.view"]
            role.save(update_fields=["permissions"])


def revoke(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    for role in Role.objects.filter(code__in=VIEWERS):
        role.permissions = [p for p in role.permissions if p != "students.view"]
        role.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(default='Nigeria', help_text='Country of residence', max_length=60),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_session',
            field=models.CharField(blank=True, help_text='Academic session the student is in', max_length=9),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jamb_reg_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='JAMB registration number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'On probation'), ('suspended', 'Suspended'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn'), ('expelled', 'Expelled'), ('completed', 'Completed (awaiting graduation)'), ('graduated', 'Graduated')], default='active', max_length=16),
        ),
        migrations.RunPython(backfill, revoke),
    ]
