# Generated by Django 5.2.17 on 2026-09-23 22:18

import apps.academics.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('units', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')], default=100)),
                ('semester_number', models.PositiveSmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('dropped', 'Dropped')], default='registered', max_length=16)),
                ('is_carryover', models.BooleanField(default=False, help_text='Re-registration of a course previously failed.')),
                ('ca_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='CA score')),
                ('exam_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('result_status', models.CharField(choices=[('pending', 'Not yet entered'), ('draft', 'Draft'), ('submitted', 'Submitted to HOD'), ('department_approved', 'Approved by HOD'), ('faculty_approved', 'Approved by Dean'), ('published', 'Published')], default='pending', max_length=24)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('degree', models.CharField(choices=[('B.Sc.', 'Bachelor of Science'), ('B.A.', 'Bachelor of Arts'), ('B.Eng.', 'Bachelor of Engineering'), ('B.Ed.', 'Bachelor of Education'), ('LL.B.', 'Bachelor of Laws'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery')], default='B.Sc.', max_length=8)),
                ('duration_years', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['course__level', 'course__semester_number', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9, validators=[apps.academics.models.validate_session])),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=True, help_text='Students may register and add/drop courses.')),
                ('tuition_per_unit', models.DecimalField(decimal_places=2, default=350, max_digits=10)),
                ('fee_due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=120)),
                ('days', models.CharField(blank=True, max_length=32)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.course')),
            ],
            options={
                'ordering': ['course__code'],
            },
        ),
    ]
