# Generated by Django 5.2.17 on 2026-09-24 10:25

import apps.students.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('active', 'Active'), ('probation', 'On probation'), ('suspended', 'Suspended'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn'), ('expelled', 'Expelled'), ('completed', 'Completed (awaiting graduation)'), ('graduated', 'Graduated')], max_length=16)),
                ('to_status', models.CharField(choices=[('active', 'Active'), ('probation', 'On probation'), ('suspended', 'Suspended'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn'), ('expelled', 'Expelled'), ('completed', 'Completed (awaiting graduation)'), ('graduated', 'Graduated')], max_length=16)),
                ('reason', models.CharField(max_length=300)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('admission_letter', 'Admission letter'), ('olevel', 'O-Level result'), ('jamb_result', 'JAMB result slip'), ('birth_certificate', 'Birth certificate'), ('lga_certificate', 'Certificate of state of origin'), ('medical', 'Medical report'), ('transcript', 'Transcript'), ('letter', 'Official letter'), ('other', 'Other')], max_length=24)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(upload_to=apps.students.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=40)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
