# Generated by Django 5.2.17 on 2026-09-24 08:18

import apps.admissions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='e.g. 2026/2027', max_length=9, unique=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('opens_on', models.DateField()),
                ('closes_on', models.DateField(help_text='Last day applications can be started, paid for or submitted.')),
                ('min_utme_score', models.PositiveSmallIntegerField(default=160, help_text='Lowest UTME score that may apply.', validators=[django.core.validators.MaxValueValidator(400)])),
                ('resumption_date', models.DateField(blank=True, help_text='Shown on admission letters.', null=True)),
                ('acceptance_deadline', models.DateField(blank=True, help_text='Last day to accept an offer.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one cycle can be active at a time.')),
            ],
            options={
                'ordering': ['-session'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_admission_cycle'), models.CheckConstraint(condition=models.Q(('closes_on__gte', models.F('opens_on'))), name='cycle_closes_after_opening')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('screening', 'Screening'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('admitted', 'Admitted'), ('accepted', 'Accepted')], db_index=True, default='draft', max_length=16)),
                ('entry_mode', models.CharField(choices=[('utme', 'UTME (100 Level)'), ('direct_entry', 'Direct Entry (200 Level)'), ('transfer', 'Inter-university transfer')], default='utme', max_length=16)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=8)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Nigerian', max_length=40)),
                ('state_of_origin', models.CharField(blank=True, max_length=40)),
                ('lga', models.CharField(blank=True, max_length=60, verbose_name='LGA')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('nin', models.CharField(blank=True, help_text='National Identification Number', max_length=11, verbose_name='NIN')),
                ('next_of_kin_name', models.CharField(blank=True, max_length=120)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=40)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('jamb_reg_number', models.CharField(blank=True, max_length=16, verbose_name='JAMB registration number')),
                ('utme_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(400)])),
                ('olevel_results', models.JSONField(blank=True, default=list)),
                ('previous_institution', models.CharField(blank=True, max_length=160)),
                ('previous_qualification', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('screening_score', models.DecimalField(blank=True, decimal_places=2, help_text='Post-UTME screening score out of 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('screening_remarks', models.CharField(blank=True, max_length=300)),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('letter_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('letter_issued_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='academics.programme')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.admissioncycle')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_choice_applications', to='academics.programme')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('second_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_choice_applications', to='academics.programme')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('passport', 'Passport photograph'), ('olevel', 'O-Level result (WAEC/NECO/NABTEB)'), ('jamb_result', 'JAMB UTME result slip'), ('birth_certificate', 'Birth certificate or age declaration'), ('lga_certificate', 'Certificate of state of origin'), ('other', 'Other supporting document')], max_length=24)),
                ('file', models.FileField(upload_to=apps.admissions.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=40)),
                ('size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admissions.application')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway', models.CharField(default='paystack', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('gateway_response', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('cycle', 'applicant'), name='one_application_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('application', 'kind'), name='one_document_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='applicationpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('application',), name='one_successful_fee_payment'),
        ),
    ]
